name: rl-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # Remove this line if you don't have a GPU
  - numpy
  - matplotlib
  - tqdm
  - pip
  - pip:
      - gymnasium
      - gymnasium[atari]
